name = "BDM Sticky ATC Bar"
client_id = "1bd9623cc54e833a0a0aec96a5fe1af4"

# ‚≠ê MUST BE ROOT URL ONLY
application_url = "https://sticky-add-to-cart-bar-pro.onrender.com"

embedded = true

[access_scopes]
scopes = "read_products,read_orders"

[auth]
redirect_urls = [
  "https://sticky-add-to-cart-bar-pro.onrender.com/auth/callback"
]

[[webhooks.subscriptions]]
topics = ["orders/paid"]
uri = "/webhooks/orders/paid"
