# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "274644b8e4ba970fe66b9a97dcbbb712"
name = "Sticky Add To Cart Bar"
application_url = "https://sticky-add-to-cart-bar-pro.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "bdm-sandbox.myshopify.com"

[webhooks]
api_version = "2024-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://sticky-add-to-cart-bar-pro.onrender.com/auth/callback"
]

[app_proxy]
url = "https://sticky-add-to-cart-bar-pro.onrender.com"
subpath = "bdm-sticky-atc"
prefix = "apps"
