name = "BDM Sticky Add to Cart Bar"
client_id = "624b866762bfee0ffea282573cfc8539"

application_url = "https://sticky-add-to-cart-bar-pro.onrender.com"
embedded = true

[auth]
redirect_urls = [
  "https://sticky-add-to-cart-bar-pro.onrender.com/auth/callback",
  "https://sticky-add-to-cart-bar-pro.onrender.com/auth/shopify/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
