name = "Sticky ATC Analytics Pixel"
type = "web_pixel_extension"
api_version = "2024-07"
runtime_context = "strict"

[extension_points]
shopify.web_pixel.render = {}

[runtime_configuration_definition]
type = "object"
