name = "Sticky ATC Analytics Pixel"
type = "web_pixel_extension"

runtime_context = "strict"

extension_points = [
  "shopify.web_pixel.render"
]

[runtime_configuration_definition]
type = "object"

[runtime_configuration_definition.properties]
